spring:
  application:
    name: market-data-service

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/finamo
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver
